* On the Meanings of the Logical Constants and the Justifications of the Logical Laws
** First Lecture
   - Logical Operators operate on *propositions* and *propositional functions*
   - Logical Laws -- ~rules of inference~ -- operate on *assertions/judgements*
   - Here ~A~, ~B~, and ~A & B~ are *affirmations* not *propositions*.
     Therefore, the affirmation of ~A~ and the affirmation of ~B~ takes us
     to the affirmation of ~A & B~.
     #+BEGIN_SRC LaTex
 |- A    |- B
--------------
  |- A & B
     #+END_SRC
   - Assertion != Proposition
   - Propositions
     - Old definition: Propositions are the things we prove.
     - Propositions are used by logical operators.
     - Propositions are always represented by complete expressions.
     - Kant introduced the word *Judgment* for that.
       - *Premises* and *Conclusions* of a logical inference are always called *Judgements*.
     - ~A~ is a proposition ~->~ new way of judgement.
       #+BEGIN_SRC LaTex
     |- A      ;; |- A is a judgement, and a premise
--------------
  |- A or B    ;; |- A or B is a judgment, and the conclusion
       #+END_SRC
     - But ~A~ and ~B~ has to be propositions, therefore
       #+BEGIN_SRC LaTex
 |- A prop  |- B prop  |- A  ;; |- A prop ~> A is a proposition
----------------------------
        |- A or B
       #+END_SRC

** Second Lecture
** Third Lecture
* Concepts
  - Assertions / Judgements
  - Propositions
  - Premises
  - Inference Rules
  - Logical Inference
  - Logical Operators
  - Enunciation vs Propositions
